# Generated by Django 4.0.1 on 2023-05-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSelections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Payment Selection',
                'verbose_name_plural': 'Payment Selections',
            },
        ),
        migrations.CreateModel(
            name='ServiceOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Required', max_length=255, verbose_name='delivery_name')),
                ('service_price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 9999.99.'}}, help_text='Maximum 9999.99', max_digits=6, verbose_name='service price')),
                ('service_method', models.CharField(choices=[('IS', 'In Home'), ('HD', 'Online'), ('DD', 'Phone')], help_text='Required', max_length=255, verbose_name='service_method')),
                ('service_timeframe', models.CharField(help_text='Required', max_length=255, verbose_name='serrvice timeframe')),
                ('service_window', models.CharField(help_text='Required', max_length=255, verbose_name='service window')),
                ('order', models.IntegerField(default=0, help_text='Required', verbose_name='list order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Option',
                'verbose_name_plural': 'Service Options',
            },
        ),
    ]
