# Generated by Django 4.0.1 on 2023-05-19 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required and unique', max_length=255, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Category safe URL')),
                ('is_active', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100, null=True)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Change country visibility', verbose_name='Country visibility')),
            ],
            options={
                'verbose_name_plural': 'Data',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Required', max_length=100, verbose_name='Role')),
                ('gender', models.CharField(max_length=1)),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='Name')),
                ('specialization', models.CharField(help_text='Required', max_length=255, verbose_name='Specialization')),
                ('bio', models.TextField(blank=True, help_text="Enter doctor's biography", null=True, verbose_name='Biography')),
                ('country', models.CharField(help_text='Required', max_length=100, null=True, verbose_name='Country')),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, help_text="Upload doctor's image", null=True, upload_to='doctor_images/', verbose_name='Image')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Change Doctor visibility', verbose_name='Doctor visibility')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, null=True)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='name')),
                ('diagnostic_equipment', models.CharField(blank=True, help_text='Not Required', max_length=255, verbose_name='diagnostic_equipment')),
                ('monitoring_sife_support_equipment', models.CharField(blank=True, help_text='Not Required', max_length=255, verbose_name='monitoring_sife_support_equipment')),
                ('surgical_equipment', models.CharField(blank=True, help_text='Not Required', max_length=255, verbose_name='surgical_equipment')),
                ('patient_care_equipment', models.CharField(blank=True, help_text='Not Required', max_length=255, verbose_name='patient_care_equipment')),
                ('emergency_trauma_equipmen', models.CharField(blank=True, help_text='Not Required', max_length=255, verbose_name='emergency_trauma_equipmen')),
                ('pharmacy_medication_management', models.CharField(blank=True, help_text='Not Required', max_length=255, verbose_name='pharmacy_medication_management')),
                ('support_ervices', models.CharField(blank=True, help_text='Not Required', max_length=255, verbose_name='support_ervices')),
                ('accreditations_certifications', models.CharField(blank=True, help_text='Not Required', max_length=255, verbose_name='accreditations_certifications')),
                ('doctor_information', models.CharField(blank=True, help_text='Not Required', max_length=255, verbose_name='doctor_information')),
                ('patient_resources', models.CharField(blank=True, help_text='Not Required', max_length=255, verbose_name='patient_resources')),
                ('wait_times', models.CharField(blank=True, help_text='Not Required', max_length=255, verbose_name='wait_times')),
                ('insurance_payment_options', models.CharField(blank=True, help_text='Not Required', max_length=255, verbose_name='insurance_payment_options')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone_number')),
                ('hospital_beds', models.IntegerField(default=0, verbose_name='hospital_beds')),
                ('website', models.URLField(verbose_name='website')),
                ('title', models.CharField(help_text='Required For Hospital Profile', max_length=255, verbose_name='title')),
                ('hospital_profiles', models.TextField(blank=True, help_text='Not Required', verbose_name='hospital_profiles')),
                ('specialties_services', models.TextField(verbose_name='disease_treatment')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, help_text='Change hospital visibility', verbose_name='Hospital visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HospitalSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Product Specification',
                'verbose_name_plural': 'Product Specifications',
            },
        ),
        migrations.CreateModel(
            name='HospitalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, unique=True, verbose_name='Hospital Name')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=250)),
                ('rate', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.hospital')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDoctors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveReportDoctors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_date', models.CharField(max_length=255)),
                ('leave_message', models.TextField()),
                ('leave_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalSpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Hospital specification value (maximum of 255 words', max_length=255, verbose_name='value')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.hospital')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.hospitalspecification')),
            ],
            options={
                'verbose_name': 'Hospital Specification Value',
                'verbose_name_plural': 'Hospital Specification Values',
            },
        ),
        migrations.AddField(
            model_name='hospitalspecification',
            name='Hospital_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.hospitaltype'),
        ),
        migrations.CreateModel(
            name='HospitalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default.png', help_text='Upload a hospital image', upload_to='images/', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, help_text='Please add alturnative text', max_length=255, null=True, verbose_name='Alturnative text')),
                ('is_feature', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_image', to='base.hospital')),
            ],
            options={
                'verbose_name': 'Hospital Image',
                'verbose_name_plural': 'Hospital Images',
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='Hospital_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.hospitaltype'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='category',
            field=models.ForeignKey(help_text='Required', on_delete=django.db.models.deletion.CASCADE, to='base.category', verbose_name='category'),
        ),
        migrations.CreateModel(
            name='FeedBackUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('feedback_reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackDoctors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('feedback_reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('appointment_date', models.DateTimeField()),
                ('country', models.CharField(help_text='Required', max_length=100, null=True, verbose_name='name')),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Change doctor visibility', verbose_name='doctor visibility')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.doctors')),
            ],
            options={
                'verbose_name_plural': 'appointments',
            },
        ),
    ]
