# Generated by Django 4.0.1 on 2023-05-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='Hospital_type',
        ),
    ]
