# Generated by Django 4.0.1 on 2023-05-19 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_hospital_hospital_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='category',
        ),
    ]
