# Generated by Django 4.0.1 on 2023-05-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_hospital_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Change Doctor visibility', verbose_name='Doctor visibility'),
        ),
    ]
