# Generated by Django 4.0.1 on 2023-05-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_doctors_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='support_ervices',
            new_name='support_services',
        ),
    ]
