# Generated by Django 4.0.1 on 2023-05-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_support_ervices_hospital_support_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='support_services',
            field=models.CharField(blank=True, help_text='Not Required', max_length=255, verbose_name='support_services'),
        ),
    ]
